### ISSUE TITLE
PvDisabler

### ISSUE THREAD

**Issue by willrogers** [willrogers/pytac#13]
This should allow enabling an element depending on the value of a PV.  It should live in the `epics.py` module.

```
class PvEnabler(object):
    __init__(self, pv, disabled_value):
        ...
```

Look up `__bool__()` and `__nonzero__()` in Python.

It should work like this:

```
pve = PvEnabler('enable-pv', 1)
if pve:
    print('enabled')
else:
    print('disabled')
```

**Comment by razvanvasile** [comment]
I added a new class PvEnabler() inside device.py

**Comment by willrogers** [comment]
Done!
